---
#
# Playbook to install the Elasticsearch and kibana
#
---
- hosts: mon
  remote_user: deployer
  become: yes
  become_user: root
  sudo: true
  roles:
    - java
    - elasticsearch
    - kibana
