# roles/base_fedora/tasks/admin.yml
#
# Settings regarding the admin user
---
- name: Make sure users from the wheel group can use sudo
  lineinfile:
    dest: /etc/sudoers.d/wheel
    state: present
    create: yes
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) ALL'
    validate: 'visudo -cf %s'
  tags:
    - fedora
    - admin


- name: Set attributes of sudo configuration file for wheel group
  file:
    path: /etc/sudoers.d/wheel
    state: file
    owner: root
    group: root
    mode: 0440
  tags:
    - fedora
    - admin
